[workspace.lints.rust]
#unsafe_code = "forbid"
unused = "allow"

[workspace]
resolver = "2"

members = [
    "crates/simwheel-embassy-async",
    "crates/simwheel-usbd-human",
]

[workspace.dependencies]
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }

